# Generated by Django 3.1.1 on 2020-09-12 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem_gen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poem_gen.author'),
        ),
    ]
