# Generated by Django 3.1.1 on 2020-09-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem_gen', '0002_auto_20200912_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='screenname',
            new_name='user',
        ),
    ]
